services:
  weather-pred:
    image: ghcr.io/neptade/applicationbigdataproject:latest
    platform: linux/amd64
    environment:
      - INPUT_PATH=/data
      - MODEL_PATH=/model
      - OUTPUT_PATH=/output
    volumes:
      - ./data:/data/
      - ./model:/model/
      - ./output:/output/
