name: Publish Docker Image to GHCR

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/weather-pred
        run: |
          # Build the Docker image
          docker build -t "${IMAGE_NAME}:latest" .

      - name: Push Docker image to GHCR
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/weather-pred
        run: |
          # Push the image to GHCR
          docker push "${IMAGE_NAME}:latest"

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
