name: Publish Docker Image to GHCR

on:
  push:
    paths:
      - '/app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          # Convert the GitHub username to lowercase using bash
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/applicationBigDataProject"
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          # Build the Docker image with the lowercase username
          docker build -t "${IMAGE_NAME_LOWER}:latest" .

      - name: Push Docker image to GHCR
        run: |
          # Convert the GitHub username to lowercase using bash
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/applicationBigDataProject"
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          # Push the image to GHCR
          docker push "${IMAGE_NAME_LOWER}:latest"

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
